#!/usr/bin/env bash
# Cross-compile Bun for Android aarch64 using Bun 1.3.14's TypeScript build system
#
# Usage: ./scripts/build-bun.sh
#
# This script:
# 1. Applies Android patches to the Bun source
# 2. Configures with --abi=android --android-ndk=<path>
# 3. Applies the Zig vendor patch (sigaction/sigprocmask bypass)
# 4. Builds with ninja
#
# The Zig vendor patch must be applied AFTER Bun's build system downloads
# its custom Zig fork, but BEFORE the Zig compilation starts. We accomplish
# this by running `--configure-only` first, then downloading Zig, then
# patching, then running the full ninja build.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/env.sh"

# Debug mode
DEBUG="${DEBUG:-}"
if [ -n "$DEBUG" ]; then
  BUILD_FLAGS="--profile=debug"
  echo "=== Building Bun v${BUN_VERSION} for Android aarch64 (DEBUG) ==="
else
  BUILD_FLAGS="--profile=release"
  echo "=== Building Bun v${BUN_VERSION} for Android aarch64 ==="
fi

# Verify prerequisites
if [ ! -d "$BUN_SRC/.git" ]; then
    echo "ERROR: Bun source not found. Run scripts/apply-patches.sh first."
    exit 1
fi

# Apply Android patches to Bun source
echo ">>> Applying Android patches to Bun source..."
cd "$BUN_SRC"
git checkout -- . 2>/dev/null || true
git clean -fd 2>/dev/null || true
if git apply --stat "$REPO_ROOT/patches/bun/android-support.patch" >/dev/null 2>&1; then
    git apply "$REPO_ROOT/patches/bun/android-support.patch"
    echo "    Bun Android patches applied successfully."
else
    echo "ERROR: Failed to apply Android patches. Check patch compatibility."
    exit 1
fi

# Compile Android support C/asm files IMMEDIATELY after git apply, before
# any other step that might remove them (git clean, configure, etc.).
# These fix TLS alignment for Bionic (p_align >= 64) and disable MTE.
echo ">>> Compiling Android support files (early)..."
ANDROID_O_DIR_EARLY="$BUN_BUILD/android-early"
mkdir -p "$ANDROID_O_DIR_EARLY"
# Use -fno-emulated-tls so extern __thread references native TLS symbols,
# matching the native .tbss section generated by android_tls_align.s
# (NDK defaults to emulated TLS which creates __emutls_v_ prefix mismatch)
ANDROID_CFLAGS="-O2 -fPIC -fno-emulated-tls"
for srcfile in android_disable_tags.c android_tls_align.c; do
    if [ -f "$BUN_SRC/src/$srcfile" ]; then
        echo "    Compiling $srcfile..."
        $ANDROID_CC $ANDROID_CFLAGS -c "$BUN_SRC/src/$srcfile" -o "$ANDROID_O_DIR_EARLY/${srcfile%.c}.o"
    fi
done
if [ -f "$BUN_SRC/src/android_tls_align.s" ]; then
    echo "    Assembling android_tls_align.s..."
    $ANDROID_CC -O2 -fPIC -c "$BUN_SRC/src/android_tls_align.s" -o "$ANDROID_O_DIR_EARLY/android_tls_align.o"
fi
echo "    Early android support objects: $(ls $ANDROID_O_DIR_EARLY/*.o 2>/dev/null | wc -l) files"

# Remove source files to prevent the post-configure compile step from
# recompiling them WITHOUT -fno-emulated-tls (which would produce
# __emutls_v_ symbol prefix mismatch).
# Post-configure code checks [ -f "$BUN_SRC/src/..." ] and if absent,
# falls back to these early-compiled objects.
rm -f "$BUN_SRC/src/android_disable_tags.c" "$BUN_SRC/src/android_tls_align.c" "$BUN_SRC/src/android_tls_align.s"

# Build TinyCC (libtcc.a) for Android — required by bun:ffi for dlopen() support
echo ">>> Building TinyCC (libtcc.a) for Android..."
"$SCRIPT_DIR/build-tinycc.sh"

# Create build directory
mkdir -p "$BUN_BUILD"

# Configure step: generate build.ninja without building
echo ">>> Configuring Bun (generating build.ninja)..."
cd "$BUN_SRC"

# The host Bun (1.3.14+) runs the TypeScript build scripts
HOST_BUN="${HOST_BUN:-bun}"

# WebKit: use prebuilt tarballs (downloads automatically).
# For Android, the build system handles cross-compilation WebKit prebuilts.
# NDK path and API level are auto-detected from env vars (ANDROID_NDK_HOME, etc.)
# by the build system's detectAndroidNdk() function.
# TinyCC support is injected post-configure into the build.ninja link step
# because the build system can't cross-compile TinyCC from source on Android.
"$HOST_BUN" run build \
    $BUILD_FLAGS \
    --abi=android \
    --arch=aarch64 \
    --configure-only \
    --webkit=prebuilt \
    --tinycc=true \
    2>&1

echo ""
echo ">>> Configure complete. Build directory: $BUN_BUILD"

# Find the build directory (the build system creates a dir under build/)
# Look for the most recently created build.ninja
BUILD_NINJA=$(find "$BUN_SRC/build" -name "build.ninja" -newer "$BUN_SRC/scripts/build.ts" 2>/dev/null | head -1)
if [ -z "$BUILD_NINJA" ]; then
    BUILD_NINJA="$BUN_SRC/build/release/build.ninja"
    if [ ! -f "$BUILD_NINJA" ]; then
        BUILD_NINJA="$BUN_SRC/build/debug/build.ninja"
    fi
fi

if [ ! -f "$BUILD_NINJA" ]; then
    echo "ERROR: build.ninja not found. Configure step may have failed."
    ls -la "$BUN_SRC/build/" 2>/dev/null || echo "    No build/ directory found"
    exit 1
fi

NINJA_DIR=$(dirname "$BUILD_NINJA")
echo "    Ninja build dir: $NINJA_DIR"

# Compile Android support C/asm files and inject them into the link step
# These fix TLS alignment (Bionic requires p_align >= 64) and disable MTE
# (Memory Tagging Extension conflicts with JSC pointer tagging).
ANDROID_O_DIR="$NINJA_DIR/android-support"
mkdir -p "$ANDROID_O_DIR"
ANDROID_O_FILES=""
ANDROID_CFLAGS="-O2 -fPIC -fno-emulated-tls"
for srcfile in android_disable_tags.c android_tls_align.c; do
    if [ -f "$BUN_SRC/src/$srcfile" ]; then
        echo "    Compiling $srcfile..."
        $ANDROID_CC $ANDROID_CFLAGS -c "$BUN_SRC/src/$srcfile" -o "$ANDROID_O_DIR/${srcfile%.c}.o"
        ANDROID_O_FILES="$ANDROID_O_FILES $ANDROID_O_DIR/${srcfile%.c}.o"
    fi
done
if [ -f "$BUN_SRC/src/android_tls_align.s" ]; then
    echo "    Assembling android_tls_align.s..."
    $ANDROID_CC -O2 -fPIC -c "$BUN_SRC/src/android_tls_align.s" -o "$ANDROID_O_DIR/android_tls_align.o"
    ANDROID_O_FILES="$ANDROID_O_FILES $ANDROID_O_DIR/android_tls_align.o"
fi
# Fallback to early-compiled objects if source files were removed
if [ -z "$ANDROID_O_FILES" ] && [ -d "$BUN_BUILD/android-early" ]; then
    echo "    Source files not found, using early-compiled objects..."
    ANDROID_O_DIR="$BUN_BUILD/android-early"
    ANDROID_O_FILES=$(ls "$ANDROID_O_DIR"/*.o 2>/dev/null || true)
fi
echo "    Android support objects: $(echo "$ANDROID_O_FILES" | wc -w) files"

# Inject prebuilt libtcc.a AND android support .o files into the link step
LIBTCC_A="$WEBKIT_OUTPUT/lib/libtcc.a"
if [ -f "$LIBTCC_A" ]; then
    echo ">>> Injecting libtcc.a and android support objects into link step..."
    # Build a single static archive with short, relative path name
    ln -sf "$NINJA_DIR" "$BUN_BUILD/ninjainput" 2>/dev/null || true
    ANDROID_A="$BUN_BUILD/android_tls.a"
    $ANDROID_AR rcs "$ANDROID_A" "$ANDROID_O_DIR"/*.o 2>/dev/null
    echo "    Created $ANDROID_A"
    # Simple sed with short relative paths
    cd "$BUN_BUILD"
    if grep -q "libtcc" "$BUILD_NINJA" 2>/dev/null; then
        echo "    libtcc.a already in build.ninja inputs"
    else
        # Add absolute paths directly — shorter than full WORK_DIR paths via symlink
        sed -i "s|^build bun: \(.*\)|build bun: \1 $ANDROID_A $LIBTCC_A|" "$BUILD_NINJA"
        echo "    Added libtcc.a and android_tls.a to bun link inputs"
    fi
else
    echo "WARNING: libtcc.a not found at $LIBTCC_A"
    echo "    TinyCC support will NOT be available. Build TinyCC first."
fi

# Try to download Zig vendor BEFORE the full build
# The zig_fetch rule is defined in the generated build.ninja
echo ">>> Downloading Zig vendor..."
cd "$NINJA_DIR"

# Try various target names for downloading Zig
ZIG_VENDOR_DIR="$BUN_SRC/vendor/zig"
if [ ! -f "$ZIG_VENDOR_DIR/zig" ] && [ ! -f "$ZIG_VENDOR_DIR/zig.exe" ]; then
    # Look for the ninja rule that downloads zig
    ZIG_TARGETS=$(grep -o 'build [^:]*: zig_fetch' "$BUILD_NINJA" 2>/dev/null | awk '{print $2}' | tr -d ':')
    if [ -n "$ZIG_TARGETS" ]; then
        for target in $ZIG_TARGETS; do
            echo "    Running ninja target: $target"
            ninja "$target" 2>&1 || true
        done
    else
        # Fallback: try to build a minimal target that triggers zig download
        echo "    No zig_fetch target found. Trying to build a minimal target..."
        # Look up the zig binary output path in build.ninja
        ZIG_BIN_PATH=$(grep -m1 "vendor/zig/zig" "$BUILD_NINJA" 2>/dev/null | head -1 | sed 's/.*build //' | sed 's/:.*//')
        if [ -n "$ZIG_BIN_PATH" ]; then
            echo "    Building zig target: $ZIG_BIN_PATH"
            ninja "$ZIG_BIN_PATH" 2>&1 || true
        fi
    fi
fi

# Apply Zig vendor patch AFTER download, BEFORE build
ZIG_POSIX="$ZIG_VENDOR_DIR/lib/std/posix.zig"
if [ -f "$ZIG_POSIX" ]; then
    echo ">>> Applying Zig vendor patch (sigaction/sigprocmask Android bypass)..."
    cd "$BUN_SRC"
    if patch --dry-run -p1 < "$REPO_ROOT/patches/zig/posix-android-sigaction.patch" >/dev/null 2>&1; then
        patch -p1 < "$REPO_ROOT/patches/zig/posix-android-sigaction.patch"
        echo "    Zig patch applied successfully."
    else
        if grep -q "comptime builtin.abi.isAndroid()" "$ZIG_POSIX" 2>/dev/null; then
            echo "    Zig patch already applied."
        else
            echo "WARNING: Zig patch doesn't match cleanly. Trying with --fuzz..."
            patch -p1 --fuzz=3 < "$REPO_ROOT/patches/zig/posix-android-sigaction.patch" || {
                echo "ERROR: Could not apply Zig patch. Manual intervention required."
                exit 1
            }
        fi
    fi
else
    echo "WARNING: Zig vendor not yet downloaded ($ZIG_POSIX not found)."
    echo "         Zig may be downloaded during the build. If the build fails,"
    echo "         re-run this script to apply the patch and retry."
fi

# Build
echo ">>> Building Bun (this will take 30-45 minutes)..."
cd "$NINJA_DIR"
ninja -j"$JOBS" 2>&1 || {
    echo ""
    echo ">>> Build failed. Checking if Zig was downloaded during the build..."
    if [ -f "$ZIG_POSIX" ] && ! grep -q "comptime builtin.abi.isAndroid()" "$ZIG_POSIX" 2>/dev/null; then
        echo ">>> Zig downloaded during build but patch not applied. Applying now..."
        cd "$BUN_SRC"
        patch -p1 < "$REPO_ROOT/patches/zig/posix-android-sigaction.patch" || {
            echo "ERROR: Zig patch failed to apply"
            exit 1
        }
        echo "    Zig patch applied. Rebuilding..."
        cd "$NINJA_DIR"
        ninja -j"$JOBS"
    else
        echo "ERROR: Build failed (Zig patch was already applied — different error)"
        exit 1
    fi
}

# Verify output: find the bun binary in the build directory
BUN_BINARY=$(find "$NINJA_DIR" -maxdepth 1 -name "bun" -o -name "bun-debug" -o -name "bun-profile" 2>/dev/null | head -1)
if [ ! -f "$BUN_BINARY" ]; then
    echo "ERROR: Bun binary not found after build"
    echo "    Searched in: $NINJA_DIR"
    ls -la "$NINJA_DIR"/bun* 2>/dev/null || echo "    No bun* files found"
    exit 1
fi

# Copy to expected location for downstream scripts
cp "$BUN_BINARY" "$BUN_BUILD/bun"

echo ""
echo "=== Bun build complete ==="
echo "Binary: $BUN_BUILD/bun"
echo "Size: $(du -h "$BUN_BUILD/bun" | cut -f1)"
file "$BUN_BUILD/bun"
